#!/usr/bin/env python3
"""
page_turn.py — a real page-turn transition, generated by code. No GUI, no editing
app, no Resolve. $0 per transition, re-renderable forever.

WHY THIS EXISTS: Resolve's free build cannot be driven from outside (its
external-scripting preference is Studio-only) and Evan never wants to open an
editor and click. So the transition is computed here, headlessly.

MODEL (v2 — the first version drew a flat white band and read as a bar):
the page is a rigid sheet hinged at the LEFT spine that rotates about the spine
axis by theta = 0..180 deg, with a semicircular CURL of radius r at its free
edge, exactly like a sheet of paper lifting from the right and folding left.

  flat part   s in [0, Lf]:   x = s*cos(theta),            depth = s*sin(theta)
  curl        s in (Lf, W]:   phi = (s-Lf)/r  (0..pi)
                              x = Lf*cos(theta) + r*(sin(theta+phi) - sin(theta))
                              depth = Lf*sin(theta) + r*(cos(theta) - cos(theta+phi))

Rendering, in order: paint the NEXT page flat in the bed, then walk the page's
own samples FARTHEST-FIRST so nearer folds occlude farther ones (a cheap painter's
algorithm with per-column writes). A sample whose surface has turned past 90 deg
is seen from BEHIND, so it is drawn as paper, not art. Depth also drives shading,
and the lifting edge casts a soft shadow on the incoming page.

  usage: page_turn.py --from a.png --to b.png --out turn.mp4 [--dur 0.9] [--fps 24]
                      [--size 1080] [--curl 0.14] [--still strip.png]
"""
import argparse
import os
import subprocess
import tempfile

import numpy as np
from PIL import Image

PAPER = np.array([252.0, 250.0, 244.0])
SAMPLES = 2600          # source samples across the page width
SHADOW_W = 0.07         # shadow band width, fraction of frame


def load(path, size):
    im = Image.open(path).convert("RGB")
    if im.size != (size, size):
        s = max(size / im.width, size / im.height)
        im = im.resize((int(im.width * s), int(im.height * s)), Image.LANCZOS)
        l, t = (im.width - size) // 2, (im.height - size) // 2
        im = im.crop((l, t, l + size, t + size))
    return np.asarray(im).astype(np.float32)


def frame(art, nxt, p, curl=0.14):
    H, W = art.shape[0], art.shape[1]
    theta = np.pi * p                                  # 0 -> 180 deg
    # The curl must NOT exist at rest: a page lying flat covers the whole frame.
    # A constant radius left 30% of the next page visible in frame 1, so the curl
    # ramps in over the first third of the turn and the sheet is full-width at p=0.
    ramp = 1.0
    if p < 0.35:
        q = p / 0.35
        ramp = q * q * (3 - 2 * q)
    r = curl * W * ramp
    if r < 2.0:                                        # flat: the art, untouched
        return np.clip(art, 0, 255).astype(np.uint8)
    Lf = max(0.0, W - np.pi * r)                        # flat length of the sheet

    # --- geometry of the sheet, sampled densely in source distance s
    s = np.linspace(0.0, W, SAMPLES)
    in_curl = s > Lf
    phi = np.where(in_curl, (s - Lf) / r, 0.0)
    x = Lf * np.cos(theta) + np.where(in_curl, r * (np.sin(theta + phi) - np.sin(theta)), 0.0)
    # distance of each source point from the free edge, so the far edge leads
    depth = Lf * np.sin(theta) + np.where(
        in_curl, r * (np.cos(theta) - np.cos(theta + phi)), 0.0)
    tang = theta + phi                                  # surface facing angle
    facing_back = np.sin(tang) < 0                      # past 90 deg -> we see paper

    out = nxt.copy()                                    # the bed = incoming page

    # --- shadow the lifting sheet casts on the incoming page
    if x.max() < W:
        cols = np.arange(W, dtype=np.float32)
        edge = x.max()
        d = cols - edge
        band = (d > 0) & (d < SHADOW_W * W)
        if band.any():
            k = 1.0 - d[band] / (SHADOW_W * W)
            lift = min(1.0, max(0.0, np.sin(theta)))     # no shadow when flat
            out[:, band] *= (1.0 - 0.5 * lift * k)[None, :, None]

    # --- paint the sheet, farthest sample first (painter's algorithm)
    order = np.argsort(-depth)
    xx = np.round(x[order]).astype(int)
    back = facing_back[order]
    s_src = s[order]
    dp = depth[order]
    zmax = max(1e-6, depth.max())

    for i in range(len(order)):
        col = xx[i]
        if col < 0 or col >= W:
            continue
        if back[i]:
            shade = 0.88 + 0.10 * (dp[i] / zmax)
            colour = PAPER * shade
        else:
            src = np.clip(s_src[i], 0, W - 1)
            x0 = int(np.floor(src))
            fx = src - x0
            x1 = min(x0 + 1, W - 1)
            colour = art[:, x0] * (1 - fx) + art[:, x1] * fx
            # shading: surfaces angled away from the viewer are darker
            f = (1.0 - np.sin(tang[order][i])) * 0.5 + 0.5
            colour = colour * (0.62 + 0.38 * f)
            # slight edge-darkening so the free edge reads as a thickness
            if s_src[i] > W - 3:
                colour = colour * 0.8
        out[:, col] = colour

    return np.clip(out, 0, 255).astype(np.uint8)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="src", required=True)
    ap.add_argument("--to", dest="dst", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--dur", type=float, default=0.9)
    ap.add_argument("--fps", type=int, default=24)
    ap.add_argument("--size", type=int, default=1080)
    ap.add_argument("--curl", type=float, default=0.14)
    ap.add_argument("--still", default=None)
    ap.add_argument("--verify", action="store_true",
                    help="assert frame 0 == the outgoing art and the last frame == the incoming art")
    args = ap.parse_args()

    a_img, b_img = load(args.src, args.size), load(args.dst, args.size)
    n = max(2, int(round(args.dur * args.fps)))
    tmp = tempfile.mkdtemp(prefix="turn-")
    keep = {int(n * k / 5) for k in range(6)} if args.still else set()
    stills = []

    for i in range(n):
        p = i / (n - 1)
        p = p * p * (3 - 2 * p)                    # ease-in-out: lift, then settle
        f = frame(a_img, b_img, p, args.curl)
        Image.fromarray(f).save(os.path.join(tmp, f"f{i:05d}.png"))
        if i in keep:
            stills.append(f)

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-framerate", str(args.fps),
                    "-i", os.path.join(tmp, "f%05d.png"), "-c:v", "libx264",
                    "-pix_fmt", "yuv420p", "-crf", "16", "-movflags", "+faststart",
                    args.out], check=True)
    print(f"page turn: {n} frames, {n/args.fps:.2f}s -> {args.out}")

    if stills:
        tile = 360
        sheet = Image.new("RGB", (tile * len(stills), tile), (16, 16, 16))
        for i, st in enumerate(stills):
            im = Image.fromarray(st)
            im.thumbnail((tile - 4, tile - 4), Image.LANCZOS)
            sheet.paste(im, (i * tile + 2, 2))
        sheet.save(args.still)
        print(f"filmstrip -> {args.still}")

    if args.verify:
        first = frame(a_img, b_img, 0.0, args.curl).astype(int)
        last = frame(a_img, b_img, 1.0, args.curl).astype(int)
        d0 = int(np.abs(first - a_img.astype(int)).max())
        d1 = int(np.abs(last - b_img.astype(int)).max())
        print(f"verify: frame 0 vs outgoing art   max delta = {d0}")
        print(f"verify: last frame vs incoming art max delta = {d1}")
        print("verify: ENDS ARE EXACT (no seam: the turn starts and finishes on our own art)"
              if d0 == 0 and d1 == 0 else "verify: ENDS DIFFER - INSPECT")
        if d0 != 0 or d1 != 0:
            raise SystemExit(2)


if __name__ == "__main__":
    main()
