#!/usr/bin/env python3
"""
build_plate.py — make the "clean plate": the illustration with the character(s)
removed, so the sprite can move without leaving a ghost behind.

  sprite (rembg cutout) -> dilated mask -> LaMa inpaint -> plate.png

Everything outside the (dilated) mask stays pixel-identical to the original
illustration; only the hole where the character stood is regenerated by the
inpainter. Verified and reported at the end of the run.

Usage: python build_plate.py <illustration.png> <cutout-rgba.png> <out-plate.png> [dilate_px]
"""
import sys

import numpy as np
from PIL import Image, ImageFilter


class LaMa:
    """big-lama torchscript, loaded with map_location='cpu'.

    simple_lama_inpainting's own loader calls torch.jit.load() with no
    map_location, which raises on this Mac ('aten::empty_strided ... CUDA
    backend') because the shipped .pt was serialised for CUDA. Loading with
    map_location='cpu' works.
    """

    def __init__(self):
        import torch
        from simple_lama_inpainting.utils import download_model, prepare_img_and_mask
        from simple_lama_inpainting.models.model import LAMA_MODEL_URL

        self._prep = prepare_img_and_mask
        self.device = torch.device("cpu")
        path = download_model(LAMA_MODEL_URL)
        self.model = torch.jit.load(path, map_location=self.device)
        self.model.eval()
        self._torch = torch

    def __call__(self, image, mask):
        img, msk = self._prep(image, mask, self.device)
        with self._torch.inference_mode():
            out = self.model(img, msk)[0].permute(1, 2, 0).detach().cpu().numpy()
        return Image.fromarray(np.clip(out * 255, 0, 255).astype(np.uint8))


def inpaint(orig, mask):
    try:
        return LaMa()(orig, mask)
    except Exception as exc:  # fall back to OpenCV Telea so the pipeline never stalls
        print(f"[warn] LaMa unavailable ({exc.__class__.__name__}: {exc}); using cv2.inpaint TELEA")
        import cv2
        arr = np.asarray(orig)
        m = (np.asarray(mask) > 32).astype(np.uint8) * 255
        return Image.fromarray(cv2.inpaint(arr, m, 5, cv2.INPAINT_TELEA))


def main():
    src, cut, out = sys.argv[1], sys.argv[2], sys.argv[3]
    dilate = int(sys.argv[4]) if len(sys.argv) > 4 else 16
    thresh = int(sys.argv[5]) if len(sys.argv) > 5 else 8

    orig = Image.open(src).convert("RGB")
    sprite = Image.open(cut).convert("RGBA")
    if sprite.size != orig.size:
        sprite = sprite.resize(orig.size, Image.LANCZOS)

    alpha = sprite.split()[-1]
    # thresh: keep only the solid character, not faint dust/speed-smear, so the
    # hole we have to regenerate is as small as the character really is.
    mask = alpha.point(lambda v: 255 if v > thresh else 0)
    # grow the hole a little so the inpainter has clean surroundings to work from
    for _ in range(max(0, dilate // 4)):
        mask = mask.filter(ImageFilter.MaxFilter(5))
    hard = mask.copy()  # the ONLY region we are allowed to change
    # feather INWARD: the blend ramp never steps outside the hole, so every
    # pixel outside it stays bit-identical to the original illustration.
    soft = mask.filter(ImageFilter.GaussianBlur(2))
    soft_arr = np.minimum(np.asarray(soft), np.asarray(hard))
    soft = Image.fromarray(soft_arr)

    filled = inpaint(orig, hard.convert("L"))

    a = (np.asarray(soft).astype(np.float32) / 255.0)[..., None]
    plate = (np.asarray(orig).astype(np.float32) * (1 - a)
             + np.asarray(filled.convert("RGB")).astype(np.float32) * a)
    plate = np.clip(plate, 0, 255).astype(np.uint8)

    orig_arr = np.asarray(orig)
    untouched = np.asarray(hard) == 0  # outside the hole
    same = np.array_equal(plate[untouched], orig_arr[untouched])
    delta = int(np.abs(plate[untouched].astype(int) - orig_arr[untouched].astype(int)).max()) if not same else 0

    Image.fromarray(plate).save(out)
    hole = int((~untouched).sum())
    print(f"plate -> {out}")
    print(f"hole (character) = {hole} px ({100.0*hole/untouched.size:.1f}% of frame), "
          f"untouched px = {untouched.sum()}, max delta in untouched area = {delta}")
    print("plate: ORIGINAL PIXELS PRESERVED OUTSIDE THE HOLE" if same else "plate: DELTA FOUND — INSPECT")


if __name__ == "__main__":
    main()
